### ISSUE TITLE
No license for source code

### ISSUE THREAD

**Issue by alandtse** [YihaoPeng/DragonbornSpeaksNaturally#15]
Please consider putting this under an open source license so we can update this when you stop. I believe there are some issues for the VR version after we enabled ESL support but we can't fix them without a license.

**Comment by SwimmingTiger** [comment]
@DougHamil wrote the original code, so if we want to put a license, we need his permission. I asked him about it but he didn't respond.

So we may not be able to place licenses for the time being. Even if I provide the license separately, the permit is incomplete.

**Comment by SwimmingTiger** [comment]
It looks like @DougHamil left Github and NexusMods shortly after I joined the project. I've been working without a license for a long time and I think you can do that too if you want.

Or the best case scenario, we can ask @DougHamil to come back and choose a license for his original project, and then my fork will inherit that license. We can try to wait for him.

**Comment by SwimmingTiger** [comment]
I've made a new license request to @DougHamil. But he didn't seem to read the original message, so I'm not sure if he'll get it this time.

![Screenshot_20240501_140810_com gbox android](https://github.com/YihaoPeng/DragonbornSpeaksNaturally/assets/4986069/a619e641-653d-4525-9834-002392f1da77)

**Comment by SwimmingTiger** [comment]
I sent an email to @DougHamil.

![Screenshot_20240501_142609](https://github.com/YihaoPeng/DragonbornSpeaksNaturally/assets/4986069/dfaf0d3a-1f30-446f-a9bd-c7d2efaedcf2)

**Comment by DougHamil** [comment]
Apologies for the unresponsiveness. I've added the MIT license to my original repo, please feel free to adopt it.

Thank you for your continued work on this mod!

**Comment by SwimmingTiger** [comment]
> I've added the MIT license to my original repo, please feel free to adopt it.

Nice. I have merged the change. Now we have a [MIT license](https://github.com/YihaoPeng/DragonbornSpeaksNaturally/blob/master/LICENSE) in my fork.

@alandtse You are welcome to make any changes to the project. :smiley:

**Comment by alandtse** [comment]
Thank you both!
