### ISSUE TITLE
Either incorrect or misleading documentation, or errors in project.

### ISSUE THREAD

**Issue by yndrelbosch** [YihaoPeng/DragonbornSpeaksNaturally#6]
Either your documentation is misleading in that we can not build this project from the source files provided, or your Visual Studio project has a multitude of errors leading to build failure.

These are the errors I have received leading to build failure: https://gist.github.com/yndrelbosch/3a177d97ebb36cdd6c625e0cf02f2637

**Comment by SwimmingTiger** [comment]
There are two issues with the project that are not compatible with VS2019:
1. The source code from SKSE64 forgot `#include <string>`. (This is weird, but it can be built in VS2017. So no one has found this error.)
2. .NET target platform v4.6.1 is not available by default in VS2019.

I have fixed it in https://github.com/YihaoPeng/DragonbornSpeaksNaturally/commit/e26224a01d171507dc396fd9e7690ebfb2a85952

1. Set `<string>` to global auto include.
2. Remove the requirements for the .NET target platform.
