### ISSUE TITLE
Add a deselect windows option

### ISSUE THREAD

**Issue by DonFlymoor** [YihaoPeng/DragonbornSpeaksNaturally#8]
For some odd reason, WMR works much better if SkyrimVR isn't selected. While there is a switchwindows commands to input key presses, there doesn't seem to be a deselectwindow command. This would at least help me get smoother performance - I could just say "stutter be gone" or "stutter return" to select or deselect it, as well as adding them into other custom commands.

**Comment by SwimmingTiger** [comment]
You can switch focus to another window with the `switchwindow` command:
````
switchwindow notepad.exe
````
If you have a notepad opened, this will transfer focus to it.

https://github.com/YihaoPeng/DragonbornSpeaksNaturally/blob/master/docs/DSN%20Key%20Commands%20Guide.md#example-4

**Comment by SwimmingTiger** [comment]
It may be possible to add a `deselectwindow` command, and Windows' minimize all windows function should be available in the Windows API.

**Comment by DonFlymoor** [comment]
That's handy. Thanks!
