### ISSUE TITLE
Add controller button presses

### ISSUE THREAD

**Issue by DonFlymoor** [YihaoPeng/DragonbornSpeaksNaturally#9]
For some reason, when I use DSN to type E I get a CTD in SkyrimVR. If I was able to send controller presses to it, the problem probably wouldn't happen. Perhaps by using vJoy we could get around that problem. 
As an example:
Greetsing=switchwindow; controllerpress vivetrackpadmiddle

**Comment by DonFlymoor** [comment]
Nevermind, that doesn't work well and I found a better solution

**Comment by SwimmingTiger** [comment]
Can you share your solution?

Oh I found it - #10.
